theme: jekyll-theme-cayman
title: Gemstone.PhasorProtocols
description: GPA Gemstone PhasorProtocols Library
github:
  repository_name: gemstone/phasor-protocols
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
